import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { api } from "~/utils/api";
import { SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Database Jemaat GKI Karawaci</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        
      <section id="home" className="relative flex min-h-screen flex-col items-center justify-start">
        {/* Background image */}
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{ backgroundImage: "url('/backgroundHome.jpg')" }}
        />

        {/* Overlay */}
        <div className="absolute inset-0 bg-[#010C3A]/80" />

        {/* Navbar */}
        <nav className="relative z-10 flex w-full items-center justify-center px-8 py-6">
          {/* Logo */}
          <div className="flex items-center space-x-2">
            <Image src="/LOGOGKI.png" alt="Logo" width={48} height={48} className="h-12 w-12" />
            <span className="text-white font-semibold text-xl">GKI Karawaci</span>
          </div>

          {/* Menu */}
          <ul className="hidden md:flex items-center space-x-8 text-white font-medium ml-120">
            <li className="hover:text-blue-400 transition cursor-pointer">Home</li>
            <li className="hover:text-blue-400 transition cursor-pointer">About</li>
            <li className="hover:text-blue-400 transition cursor-pointer">Location</li>
            <li>
              <SignedOut>
                <SignInButton mode="modal">
                  <button className="px-5 py-2 rounded-full border border-white text-white hover:bg-white hover:text-[#0f172a] transition">
                    Login
                  </button>
                </SignInButton>
              </SignedOut>
              <SignedIn>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </li>
          </ul>
        </nav>

        {/* Hero text */}
        <div className="relative z-10 flex flex-col items-start justify-start flex-1 text-left pl-6 md:pr-80 pt-20">
          <h1 className="text-5xl md:text-6xl font-bold text-white">
            Welcome
          </h1>

          <p className="mt-6 text-lg md:text-lg text-gray-300 max-w-2xl">
            Temukan informasi lengkap tentang kehadiran dan keterlibatan jemaat dalam ibadah dan pelayanan. 
            Mari kita bersama meninjau pertumbuhan komunitas kita, sebagai bagian dari panggilan 
            untuk terus bertumbuh dalam iman dan kesetiaan.
          </p>

          <button className="mt-15 px-6 py-3 bg-blue-500 hover:bg-blue-800 text-white font-medium rounded-lg shadow-lg transition">
            Bergabung dengan kami sekarang →
          </button>
        </div>

        {/* White Box Section */}
        <div className="absolute -bottom-16 left-1/2 transform -translate-x-1/2 w-11/12 md:w-3/4 bg-white rounded-2xl shadow-lg p-8 grid grid-cols-2 md:grid-cols-3 gap-6 ">
          <div className="text-center">
            <div className="text-gray-600 font-semibold">Statistik Ibadah</div>
            <div className="text-xl font-bold">123</div>
          </div>
          <div className="text-center">
            <div className="text-gray-600 font-semibold">Jumlah Jemaat</div>
            <div className="text-xl font-bold">456</div>
          </div>
          <div className="hidden md:block text-center">
            <div className="text-gray-600 font-semibold">Pelayanan Aktif</div>
            <div className="text-xl font-bold">78</div>
          </div>
        </div>
      </section>

          
 
    </>
  );
}
