import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { SignedOut, UserButton, SignedIn } from "@clerk/nextjs";
import { useEffect, useState } from "react";

export default function Home() {
  const [activeSection, setActiveSection] = useState<string>("home");
  const [showNavbar, setShowNavbar] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);

  const handleScroll = () => {
    if (window.scrollY > lastScrollY) {
      // Scroll ke bawah
      setShowNavbar(false);
    } else {
      // Scroll ke atas
      setShowNavbar(true);
    }
    setLastScrollY(window.scrollY);
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [lastScrollY]);


  useEffect(() => {
    const sections = document.querySelectorAll("section");
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        });
      },
      { threshold: 0.6 }
    );

    sections.forEach((section) => observer.observe(section));
    return () => {
      sections.forEach((section) => observer.unobserve(section));
    };
  }, []);

  return (
    <>
      <Head>
        <title>Database Jemaat GKI Karawaci</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/LOGOGKI.png" />
      </Head>

      {/* HOME */}
      <section id="home" className="relative flex min-h-screen flex-col items-center justify-start">
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{ backgroundImage: "url('/backgroundHome.jpg')" }}
        />
        <div className="absolute inset-0 bg-[#0f172a]/80" />
        <nav
          className={`fixed top-0 left-0 z-50 flex w-full items-center justify-center px-8 py-6 bg-[#0f172a]/60 backdrop-blur-sm transition-transform duration-300 ${
            showNavbar ? "translate-y-0" : "-translate-y-full"
          }`}
        >
          <div className="flex items-center space-x-4">
            <Image src="/LOGOGKI.png" alt="Logo" width={48} height={48} className="h-12 w-12" />
            <span className="text-white font-semibold text-xl">GKI Karawaci</span>
          </div>

          <ul className="hidden md:flex items-center space-x-8 text-white font-medium ml-120">
            <li
              className={`cursor-pointer transition ${
                activeSection === "home"
                  ? "text-blue-400 font-bold underline underline-offset-4"
                  : "hover:text-blue-400"
              }`}
            >
              <a href="#home">Home</a>
            </li>
            <li
              className={`cursor-pointer transition ${
                activeSection === "about"
                  ? "text-blue-400 font-bold underline underline-offset-4"
                  : "hover:text-blue-400"
              }`}
            >
              <a href="#about">About</a>
            </li>
            <li
              className={`cursor-pointer transition ${
                activeSection === "location"
                  ? "text-blue-400 font-bold underline underline-offset-4"
                  : "hover:text-blue-400"
              }`}
            >
              <a href="#location">Location</a>
            </li>

            <li>
              <SignedOut>
                <Link href="/login">
                  <button className="px-5 py-2 rounded-full border border-white text-white hover:bg-white hover:text-[#0f172a] transition">
                    Login
                  </button>
                </Link>
              </SignedOut>

              <SignedIn>
                <div className="flex items-center gap-3">
                  <Link href="/selectDate">
                    <button className="px-4 py-2 rounded-full border border-white text-white hover:bg-blue-300 hover:text-[#0f172a] transition">
                      Daftar Hadir
                    </button>
                  </Link>

                  <UserButton afterSignOutUrl="/" />
                </div>
              </SignedIn>
            </li>
          </ul>
        </nav>

        <div className="relative z-10 flex flex-col items-start justify-start flex-1 text-left pl-6 md:pr-80 pt-40">
          <h1 className="text-5xl md:text-6xl font-bold text-white">Welcome</h1>
          <p className="mt-6 text-lg text-gray-300 max-w-2xl">
            Temukan informasi lengkap tentang kehadiran dan keterlibatan jemaat dalam ibadah dan
            pelayanan. Mari kita bersama meninjau pertumbuhan komunitas kita, sebagai bagian dari
            panggilan untuk terus bertumbuh dalam iman dan kesetiaan.
          </p>
          <SignedOut>
            <Link href="/login">
              <button className="mt-10 px-6 py-3 bg-blue-500 hover:bg-blue-800 text-white font-medium rounded-lg shadow-lg transition">
                Bergabung dengan kami sekarang →
              </button>
            </Link>
          </SignedOut>
        </div>

        {/* Statistik */}
        <div className="absolute -bottom-16 left-1/2 transform -translate-x-1/2 w-11/12 md:w-3/4 bg-white rounded-2xl shadow-lg p-8 grid grid-cols-2 md:grid-cols-3 gap-6 z-20">
          <div className="text-center">
            <div className="text-gray-600 font-semibold">Statistik Ibadah</div>
            <div className="text-xl font-bold">xxx</div>
          </div>
          <div className="text-center">
            <div className="text-gray-600 font-semibold">Jumlah Jemaat</div>
            <div className="text-xl font-bold">xxx</div>
          </div>
          <div className="hidden md:block text-center">
            <div className="text-gray-600 font-semibold">Pelayanan Aktif</div>
            <div className="text-xl font-bold">xxx</div>
          </div>
        </div>
      </section>

      {/* ABOUT */}
      <section id="about" className="relative flex min-h-screen flex-col items-center justify-start bg-gray-200">
        <div className="container mx-auto px-6 py-33 md:px-12 flex flex-col md:flex-row items-center gap-12">
          <div className="flex-1 text-center md:text-left ml-33">
            <h2 className="text-4xl md:text-4xl font-bold text-gray-800 mb-4">
              Aplikasi Monitoring dan Analisis Jemaat Gereja
            </h2>
            <p className="text-gray-600 leading-relaxed text-lg mb-6">
              Aplikasi ini menyajikan data jemaat dalam bentuk tabel yang mudah diakses serta
              dilengkapi dengan statistik visual seperti grafik usia, jumlah kehadiran, dan
              pertumbuhan jemaat, sehingga memudahkan gereja dalam mengelola dan menganalisis
              informasi secara efektif.
            </p>
            <SignedOut>
              <Link href="/login">
                <button className="bg-blue-500 text-white font-semibold mt-5 px-6 py-2 rounded-md shadow hover:bg-blue-700 text-sm transition">
                  Lihat lebih lanjut
                </button>
              </Link>
            </SignedOut>
          </div>

          <div className="flex-1 ml-30">
            <Image
              src="/pic_sectionAbout.jpeg"
              alt="Gereja"
              width={300}
              height={400}
              className="rounded-lg shadow-md"
            />
          </div>
        </div>
      </section>

      {/* LOCATION */}
      <section
        id="location"
        className="relative flex min-h-screen flex-col md:flex-row items-center justify-center w-full bg-gray-200 px-8 md:px-20 gap-10"
      >
        <div className="flex-1 py-28 text-center md:text-left ml-33">
          <h2 className="text-4xl md:text-4xl font-bold text-gray-800 mb-6">Lokasi Kami</h2>
          <p className="text-gray-600 text-base mb-6 max-w-lg">
            GKI Karawaci berlokasi di pusat kota yang mudah dijangkau. Silakan kunjungi kami untuk
            ibadah Minggu maupun kegiatan pelayanan lainnya.
          </p>
          <div className="space-y-2 text-base text-gray-700">
            <p>
              <strong>📍 Alamat:</strong> Ruko Villa Permata Blok C1 No. 3&8, Binong, Kec. Curug,
              Kabupaten Tangerang, Banten 15810
            </p>
            <p>
              <strong>☎️ Telepon:</strong> (021) 5919627
            </p>
            <p>
              <strong>⏰ Ibadah Minggu (umum):</strong> 07:00 WIB, 10:00 WIB, dan 17:00 WIB
            </p>
          </div>
        </div>

        <div className="flex-1 w-full h-[400px] rounded-xl overflow-hidden border border-gray-300 shadow-lg transform transition duration-400 hover:scale-105 hover:shadow-2xl mr-39">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.2383962737383!2d106.59043107591536!3d-6.224364961099932!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69fe82a69a373d%3A0xb96c66e99204f60c!2sGKI%20Karawaci!5e0!3m2!1sid!2sid!4v1703932000000!5m2!1sid!2sid"
            width="100%"
            height="100%"
            style={{ border: 0 }}
            allowFullScreen
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
          ></iframe>
        </div>
      </section>

      <footer className="w-full bg-[#0f172a] text-white py-10 ">
        <div className="container mx-auto px-6 md:px-12 flex flex-col md:flex-row justify-center items-center gap-6">
          <div className="text-center md:text-left">
            <h3 className="text-xl font-bold">GKI Karawaci</h3>
            <p className="text-sm text-gray-300 mt-2">
              Ruko Villa Permata Blok C1 No. 3&8, Binong, Tangerang, Banten 15810
            </p>
          </div>

          <div className="text-sm text-gray-200 text-center md:text-right ml-70">
            © 2025 GKI Karawaci. All rights reserved.
          </div>
        </div>
      </footer>
    </>
  );
}
